import { mutation } from "./_generated/server";
import { v } from "convex/values";
import { contentTypeValidator } from "./types/embeddings";

/**
 * Vector Search Mutations
 * 
 * Minimal mutation endpoints for storing embeddings generated by the backend.
 * Backend generates embeddings → sends to /api/vectorSearch/mutate → stores in contentEmbeddings table.
 */

export const mutateEmbedding = mutation({
  args: {
    operation: v.string(),
    userId: v.string(),
    contentId: v.optional(v.string()),
    contentType: v.optional(contentTypeValidator),
    embedding: v.optional(v.array(v.float64())),
    title: v.optional(v.string()),
    content: v.optional(v.string()),
    metadata: v.optional(v.any()),
  },
  returns: v.object({
    success: v.boolean(),
    data: v.optional(v.any()),
    error: v.optional(v.string()),
  }),
  handler: async (ctx, args) => {
    try {
      if (args.operation === "create_embedding_record") {
        // Validate required fields
        if (!args.contentId || !args.contentType || !args.embedding || !args.title || !args.content) {
          return {
            success: false,
            error: "Missing required fields for create_embedding_record",
          };
        }

        // Insert embedding into contentEmbeddings table
        const now = Date.now();
        const embeddingId = await ctx.db.insert("contentEmbeddings", {
          userId: args.userId,
          contentId: args.contentId,
          contentType: args.contentType,
          title: args.title,
          content: args.content,
          embedding: args.embedding,
          metadata: args.metadata || {},
          createdAt: now,
          updatedAt: now,
        });

        return {
          success: true,
          data: {
            id: embeddingId,
            contentId: args.contentId,
            contentType: args.contentType,
          },
        };
      }

      return {
        success: false,
        error: `Unknown operation: ${args.operation}`,
      };
    } catch (error) {
      console.error(`Embedding mutation error:`, error);
      return {
        success: false,
        error: error instanceof Error ? error.message : "Unknown error",
      };
    }
  },
});

