import { mutation } from "./_generated/server";
import { v } from "convex/values";
import { contentTypeValidator } from "./types/embeddings";

/**
 * Vector Search Mutations
 * 
 * Minimal mutation endpoints for storing embeddings generated by the backend.
 * Backend generates embeddings → sends to /api/vectorSearch/mutate → stores in contentEmbeddings table.
 */

export const mutateEmbedding = mutation({
  args: {
    operation: v.string(),
    userId: v.string(),
    contentId: v.optional(v.string()),
    contentType: v.optional(contentTypeValidator),
    embedding: v.optional(v.array(v.float64())),
    title: v.optional(v.string()),
    content: v.optional(v.string()),
    metadata: v.optional(v.any()),
  },
  returns: v.object({
    success: v.boolean(),
    data: v.optional(v.any()),
    error: v.optional(v.string()),
  }),
  handler: async (ctx, args) => {
    try {
      console.log(`🔍 [MUTATE_EMBEDDING] Operation: ${args.operation}, ContentId: ${args.contentId}, ContentType: ${args.contentType}`);
      
      if (args.operation === "create_embedding_record") {
        // Validate required fields with detailed error messages
        const missingFields = [];
        if (!args.contentId) missingFields.push("contentId");
        if (!args.contentType) missingFields.push("contentType");
        if (!args.embedding || !Array.isArray(args.embedding) || args.embedding.length === 0) missingFields.push("embedding");
        if (!args.title || args.title.trim() === "") missingFields.push("title");
        if (!args.content || args.content.trim() === "") missingFields.push("content");
        
        if (missingFields.length > 0) {
          console.error(`❌ [MUTATE_EMBEDDING] Missing required fields: ${missingFields.join(", ")}`);
          console.error(`❌ [MUTATE_EMBEDDING] Field values - contentId: "${args.contentId}", contentType: "${args.contentType}", embedding: ${args.embedding?.length || 0} dims, title: "${args.title}", content: ${args.content?.length || 0} chars`);
          return {
            success: false,
            error: `Missing required fields for create_embedding_record: ${missingFields.join(", ")}`,
          };
        }

        console.log(`🔄 [MUTATE_EMBEDDING] Storing embedding for ${args.contentType} ${args.contentId} (embedding dim: ${args.embedding?.length})`);

        // Insert embedding into contentEmbeddings table
        const now = Date.now();
        const embeddingId = await ctx.db.insert("contentEmbeddings", {
          userId: args.userId,
          contentId: args.contentId,
          contentType: args.contentType,
          title: args.title,
          content: args.content,
          embedding: args.embedding,
          metadata: args.metadata || {},
          createdAt: now,
          updatedAt: now,
        });

        console.log(`✅ [MUTATE_EMBEDDING] Successfully stored embedding ${embeddingId} for ${args.contentType} ${args.contentId}`);

        return {
          success: true,
          data: {
            id: embeddingId,
            contentId: args.contentId,
            contentType: args.contentType,
          },
        };
      }

      return {
        success: false,
        error: `Unknown operation: ${args.operation}`,
      };
    } catch (error) {
      console.error(`Embedding mutation error:`, error);
      return {
        success: false,
        error: error instanceof Error ? error.message : "Unknown error",
      };
    }
  },
});

