import React from 'react'
import Link from 'next/link'

export default function Privacy() {
  return (
    <div className="max-w-none">
      {/* Header Navigation */}
      <nav className="mb-12">
        <Link 
          href="/" 
          className="inline-flex items-center text-gray-600 hover:text-gray-900 transition-colors duration-200 font-medium"
        >
          <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
          </svg>
          Back to Home
        </Link>
      </nav>

      {/* Document Header */}
      <header className="mb-16 border-b border-gray-200 pb-8">
        <h1 className="text-5xl font-light text-gray-900 mb-4 tracking-tight">
          Privacy Policy
        </h1>
        <p className="text-lg text-gray-600">
          Last updated: June 06, 2025
        </p>
        <p className="mt-4 text-base text-gray-700">
          This Privacy Policy describes how Divertissement AI, Inc. ("we", "us", or "our") collects, uses, and discloses your information when you use HeyContent. It also explains your privacy rights and how the law protects you. By using HeyContent, you agree to the collection and use of information in accordance with this Privacy Policy.
        </p>
      </header>

      <article className="space-y-12 text-gray-800 leading-relaxed">
        {/* Interpretation and Definitions */}
        <section className="space-y-6">
          <h2 className="text-3xl font-medium text-gray-900 border-b border-gray-100 pb-3">Interpretation and Definitions</h2>
          <h3 className="text-xl font-medium text-gray-900">Interpretation</h3>
          <p>The words with initial capital letters have meanings defined below. These definitions apply regardless of whether they appear in singular or plural.</p>
          <h3 className="text-xl font-medium text-gray-900">Definitions</h3>
          <ul className="space-y-2 ml-6">
            <li><strong>Account</strong>: A unique account created for you to access HeyContent.</li>
            <li><strong>Company</strong>: Divertissement AI, Inc. ("we", "us", or "our").</li>
            <li><strong>Cookies</strong>: Small files placed on your device by a website, containing details of your browsing history and preferences.</li>
            <li><strong>Country</strong>: California, United States.</li>
            <li><strong>Device</strong>: Any device that can access HeyContent, such as a computer, phone, or tablet.</li>
            <li><strong>Personal Data</strong>: Any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong>: The HeyContent website and platform.</li>
            <li><strong>Service Provider</strong>: Any natural or legal person who processes data on behalf of the Company, including third-party companies or individuals who help provide or analyze the Service.</li>
            <li><strong>Third-party Social Media Service</strong>: Any website or social network through which a user can log in or create an account to use HeyContent (e.g., Google, Instagram, YouTube).</li>
            <li><strong>Usage Data</strong>: Data collected automatically, either generated by the use of HeyContent or from the platform infrastructure itself (e.g., duration of a page visit).</li>
            <li><strong>Website</strong>: HeyContent, accessible from <a href="https://www.heycontent.co/" className="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">https://www.heycontent.co/</a></li>
            <li><strong>You</strong>: The individual accessing or using HeyContent, or the company or other legal entity on behalf of which such individual is accessing or using HeyContent, as applicable.</li>
          </ul>
        </section>

        {/* Collecting and Using Your Personal Data */}
        <section className="space-y-6">
          <h2 className="text-3xl font-medium text-gray-900 border-b border-gray-100 pb-3">Collecting and Using Your Personal Data</h2>
          <h3 className="text-xl font-medium text-gray-900">Types of Data Collected</h3>
          <h4 className="text-lg font-medium text-gray-900">Personal Data</h4>
          <p>We may ask you to provide certain personally identifiable information that can be used to contact or identify you. This may include, but is not limited to:</p>
          <ul className="space-y-2 ml-6">
            <li>Email address</li>
            <li>First and last name</li>
            <li>Profile information</li>
            <li>Usage Data</li>
          </ul>
          <h4 className="text-lg font-medium text-gray-900">Usage Data</h4>
          <p>Usage Data is collected automatically when using HeyContent. This may include information such as your device's IP address, browser type, browser version, the pages you visit, the time and date of your visit, time spent on those pages, unique device identifiers, and other diagnostic data.</p>
          <h4 className="text-lg font-medium text-gray-900">Information from Third-Party Social Media Services</h4>
          <p>HeyContent allows you to connect your account to Google, Instagram, and YouTube. If you choose to connect, we may collect information associated with those accounts, such as your name, email address, and analytics or engagement data, as permitted by your settings and the third-party's policies.</p>
          <h4 className="text-lg font-medium text-gray-900">Cookies and Tracking Technologies</h4>
          <p>We use cookies and similar tracking technologies to track activity on HeyContent and store certain information. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some parts of HeyContent. For more information, see our <Link href="/legal/security" className="text-blue-600 hover:underline">Cookie Policy</Link>.</p>
        </section>

        {/* Use of Your Personal Data */}
        <section className="space-y-6">
          <h3 className="text-xl font-medium text-gray-900">How We Use Your Personal Data</h3>
          <ul className="space-y-2 ml-6">
            <li>To provide and maintain HeyContent, including to monitor usage and improve the Service.</li>
            <li>To manage your account and provide you with access to features.</li>
            <li>To contact you with updates or information related to HeyContent.</li>
            <li>To provide you with personalized insights, analytics, and recommendations.</li>
            <li>To facilitate integrations with third-party services, with your consent.</li>
            <li>To comply with legal obligations.</li>
          </ul>
        </section>

        {/* Sharing Your Personal Data */}
        <section className="space-y-6">
          <h3 className="text-xl font-medium text-gray-900">Sharing Your Personal Data</h3>
          <ul className="space-y-2 ml-6">
            <li>With service providers who help us operate and improve HeyContent.</li>
            <li>With business partners, with your consent, to offer you certain features or opportunities.</li>
            <li>For legal reasons, if required by law or to protect the rights and safety of HeyContent or others.</li>
            <li>With your consent, for any other purpose disclosed to you at the time of collection.</li>
          </ul>
        </section>

        {/* Retention of Your Personal Data */}
        <section className="space-y-6">
          <h3 className="text-xl font-medium text-gray-900">Retention of Your Personal Data</h3>
          <p>We retain your personal data only as long as necessary for the purposes set out in this Privacy Policy, or as required by law. You may request deletion of your data at any time by deleting your account or contacting us.</p>
        </section>

        {/* Transfer of Your Personal Data */}
        <section className="space-y-6">
          <h3 className="text-xl font-medium text-gray-900">Transfer of Your Personal Data</h3>
          <p>Your information may be processed and stored in countries other than your own. By using HeyContent, you consent to such transfers. We take reasonable steps to ensure your data is treated securely and in accordance with this Privacy Policy.</p>
        </section>

        {/* Delete Your Personal Data */}
        <section className="space-y-6">
          <h3 className="text-xl font-medium text-gray-900">Delete Your Personal Data</h3>
          <p>You may delete your account and associated data at any time from within HeyContent. We may retain certain information as required by law or for legitimate business purposes.</p>
        </section>

        {/* Children's Privacy */}
        <section className="space-y-6">
          <h2 className="text-3xl font-medium text-gray-900 border-b border-gray-100 pb-3">Children's Privacy</h2>
          <p>HeyContent is not intended for anyone under the age of 13. We do not knowingly collect personal information from children under 13. If you believe a child has provided us with personal data, please contact us and we will take steps to remove that information.</p>
        </section>

        {/* Links to Other Websites */}
        <section className="space-y-6">
          <h2 className="text-3xl font-medium text-gray-900 border-b border-gray-100 pb-3">Links to Other Websites</h2>
          <p>HeyContent may contain links to other websites not operated by us. We are not responsible for the content or privacy practices of those sites. We encourage you to review the privacy policy of every site you visit.</p>
        </section>

        {/* Changes to this Privacy Policy */}
        <section className="space-y-6">
          <h2 className="text-3xl font-medium text-gray-900 border-b border-gray-100 pb-3">Changes to this Privacy Policy</h2>
          <p>We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date. You are advised to review this Privacy Policy periodically for any changes.</p>
        </section>

        {/* Contact Section */}
        <section className="space-y-6 border-t border-gray-200 pt-12">
          <h2 className="text-3xl font-medium text-gray-900 border-b border-gray-100 pb-3">Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, you can contact us at <a href="mailto:hello@divertissement.ai" className="text-blue-600 hover:underline">hello@divertissement.ai</a>.</p>
        </section>
      </article>
    </div>
  );
} 