/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as a2aMutations from "../a2aMutations.js";
import type * as a2aQueries from "../a2aQueries.js";
import type * as agnoRunEvents from "../agnoRunEvents.js";
import type * as ambientInsights from "../ambientInsights.js";
import type * as apiKeys from "../apiKeys.js";
import type * as apiKeysMutations from "../apiKeysMutations.js";
import type * as apiKeysQueries from "../apiKeysQueries.js";
import type * as artifactMutations from "../artifactMutations.js";
import type * as artifactQueries from "../artifactQueries.js";
import type * as artifactVersionQueries from "../artifactVersionQueries.js";
import type * as assignmentFingerprintMutations from "../assignmentFingerprintMutations.js";
import type * as assignmentFingerprintQueries from "../assignmentFingerprintQueries.js";
import type * as auth from "../auth.js";
import type * as backgroundJobs from "../backgroundJobs.js";
import type * as briefingRoomHelpers from "../briefingRoomHelpers.js";
import type * as briefingRoomInternal from "../briefingRoomInternal.js";
import type * as briefingRoomMutations from "../briefingRoomMutations.js";
import type * as briefingRoomQueries from "../briefingRoomQueries.js";
import type * as chatModelSelectionBandit from "../chatModelSelectionBandit.js";
import type * as chatMutations from "../chatMutations.js";
import type * as chatQueries from "../chatQueries.js";
import type * as chatgptImport from "../chatgptImport.js";
import type * as claudeImport from "../claudeImport.js";
import type * as cognitiveMutations from "../cognitiveMutations.js";
import type * as cognitiveQueries from "../cognitiveQueries.js";
import type * as contentAccessHelpers from "../contentAccessHelpers.js";
import type * as contentSharingMutations from "../contentSharingMutations.js";
import type * as contentSharingQueries from "../contentSharingQueries.js";
import type * as contextEnrichmentBandit from "../contextEnrichmentBandit.js";
import type * as contextUsageMutations from "../contextUsageMutations.js";
import type * as contextUsageQueries from "../contextUsageQueries.js";
import type * as convergenceBestConfigMutations from "../convergenceBestConfigMutations.js";
import type * as convergenceBestConfigQueries from "../convergenceBestConfigQueries.js";
import type * as convergenceCurrentConfigMutations from "../convergenceCurrentConfigMutations.js";
import type * as convergenceCurrentConfigQueries from "../convergenceCurrentConfigQueries.js";
import type * as convergenceOptimizationRuns from "../convergenceOptimizationRuns.js";
import type * as convergencePresetMutations from "../convergencePresetMutations.js";
import type * as convergencePresetQueries from "../convergencePresetQueries.js";
import type * as convergenceStorageMutations from "../convergenceStorageMutations.js";
import type * as convergenceStorageQueries from "../convergenceStorageQueries.js";
import type * as conversationSummariesMutations from "../conversationSummariesMutations.js";
import type * as conversationSummariesQueries from "../conversationSummariesQueries.js";
import type * as crons from "../crons.js";
import type * as crystalCache from "../crystalCache.js";
import type * as crystalContextOptimized from "../crystalContextOptimized.js";
import type * as crystalMutations from "../crystalMutations.js";
import type * as crystalQueries from "../crystalQueries.js";
import type * as feedback from "../feedback.js";
import type * as folderMutations from "../folderMutations.js";
import type * as folderQueries from "../folderQueries.js";
import type * as formationMutations from "../formationMutations.js";
import type * as formationQueries from "../formationQueries.js";
import type * as friendshipMutations from "../friendshipMutations.js";
import type * as friendshipQueries from "../friendshipQueries.js";
import type * as http from "../http.js";
import type * as intelligenceActions from "../intelligenceActions.js";
import type * as intelligenceBandit from "../intelligenceBandit.js";
import type * as intelligenceConfig from "../intelligenceConfig.js";
import type * as intelligenceMutations from "../intelligenceMutations.js";
import type * as intelligenceQueries from "../intelligenceQueries.js";
import type * as internal_ from "../internal.js";
import type * as lib_hash from "../lib/hash.js";
import type * as messagesMutations from "../messagesMutations.js";
import type * as messagesQueries from "../messagesQueries.js";
import type * as migrations_fixFreeTierSubscriptions from "../migrations/fixFreeTierSubscriptions.js";
import type * as migrations_migrateConversationMessages from "../migrations/migrateConversationMessages.js";
import type * as migrations_migrateFingerprintsToAssignments from "../migrations/migrateFingerprintsToAssignments.js";
import type * as migrations_migrateReservedShards from "../migrations/migrateReservedShards.js";
import type * as migrations_migrateToConvexWidgetIds from "../migrations/migrateToConvexWidgetIds.js";
import type * as migrations_migrateWidgetsToIndividualDocs from "../migrations/migrateWidgetsToIndividualDocs.js";
import type * as migrations_runMigration from "../migrations/runMigration.js";
import type * as migrations from "../migrations.js";
import type * as noteMutations from "../noteMutations.js";
import type * as noteQueries from "../noteQueries.js";
import type * as noteSharing from "../noteSharing.js";
import type * as notes from "../notes.js";
import type * as operationalTransform from "../operationalTransform.js";
import type * as paginatedQueries from "../paginatedQueries.js";
import type * as platformRouter from "../platformRouter.js";
import type * as presence from "../presence.js";
import type * as priceConfig from "../priceConfig.js";
import type * as projectContentQueries from "../projectContentQueries.js";
import type * as projectPresence from "../projectPresence.js";
import type * as projectWidgetsMutations from "../projectWidgetsMutations.js";
import type * as projectWidgetsQueries from "../projectWidgetsQueries.js";
import type * as projectsMutations from "../projectsMutations.js";
import type * as projectsQueries from "../projectsQueries.js";
import type * as promptsMutations from "../promptsMutations.js";
import type * as promptsQueries from "../promptsQueries.js";
import type * as rateLimiting from "../rateLimiting.js";
import type * as referrals from "../referrals.js";
import type * as setAdminRole from "../setAdminRole.js";
import type * as shardLifecycleMutations from "../shardLifecycleMutations.js";
import type * as shardLifecycleQueries from "../shardLifecycleQueries.js";
import type * as shardMutations from "../shardMutations.js";
import type * as shardQueries from "../shardQueries.js";
import type * as shardStatusManager from "../shardStatusManager.js";
import type * as stardustMutations from "../stardustMutations.js";
import type * as stardustQueries from "../stardustQueries.js";
import type * as subscriptionActions from "../subscriptionActions.js";
import type * as subscriptionPlansMutations from "../subscriptionPlansMutations.js";
import type * as subscriptionPlansQueries from "../subscriptionPlansQueries.js";
import type * as subscriptionQueries from "../subscriptionQueries.js";
import type * as testHelpers from "../testHelpers.js";
import type * as toolCallMutations from "../toolCallMutations.js";
import type * as translationMutations from "../translationMutations.js";
import type * as translationQueries from "../translationQueries.js";
import type * as types_a2aNote from "../types/a2aNote.js";
import type * as types_agnoRunEvent from "../types/agnoRunEvent.js";
import type * as types_ambientInsight from "../types/ambientInsight.js";
import type * as types_apiKey from "../types/apiKey.js";
import type * as types_artifact from "../types/artifact.js";
import type * as types_artifactVersion from "../types/artifactVersion.js";
import type * as types_assignmentFingerprint from "../types/assignmentFingerprint.js";
import type * as types_backgroundJob from "../types/backgroundJob.js";
import type * as types_backgroundJobs from "../types/backgroundJobs.js";
import type * as types_briefingCluster from "../types/briefingCluster.js";
import type * as types_briefingEvent from "../types/briefingEvent.js";
import type * as types_briefingPreferences from "../types/briefingPreferences.js";
import type * as types_chatModelSelectionArm from "../types/chatModelSelectionArm.js";
import type * as types_chatModelSelectionDecision from "../types/chatModelSelectionDecision.js";
import type * as types_cognitiveField from "../types/cognitiveField.js";
import type * as types_contentEmbedding from "../types/contentEmbedding.js";
import type * as types_contextEnrichmentArm from "../types/contextEnrichmentArm.js";
import type * as types_contextEnrichmentDecision from "../types/contextEnrichmentDecision.js";
import type * as types_contextUsage from "../types/contextUsage.js";
import type * as types_convergenceBestConfig from "../types/convergenceBestConfig.js";
import type * as types_convergenceCurrentConfig from "../types/convergenceCurrentConfig.js";
import type * as types_convergencePresetConfig from "../types/convergencePresetConfig.js";
import type * as types_convergenceStorage from "../types/convergenceStorage.js";
import type * as types_conversation from "../types/conversation.js";
import type * as types_conversationSummary from "../types/conversationSummary.js";
import type * as types_crystal from "../types/crystal.js";
import type * as types_crystalCache from "../types/crystalCache.js";
import type * as types_crystalFormationRun from "../types/crystalFormationRun.js";
import type * as types_crystalIntelligence from "../types/crystalIntelligence.js";
import type * as types_dataImport from "../types/dataImport.js";
import type * as types_embeddingQueue from "../types/embeddingQueue.js";
import type * as types_embeddingSync from "../types/embeddingSync.js";
import type * as types_embeddingUpdate from "../types/embeddingUpdate.js";
import type * as types_embeddings from "../types/embeddings.js";
import type * as types_feedback from "../types/feedback.js";
import type * as types_folder from "../types/folder.js";
import type * as types_friendship from "../types/friendship.js";
import type * as types_index from "../types/index.js";
import type * as types_intelligenceBandit from "../types/intelligenceBandit.js";
import type * as types_intelligenceBanditArm from "../types/intelligenceBanditArm.js";
import type * as types_intelligenceBanditDecision from "../types/intelligenceBanditDecision.js";
import type * as types_intelligenceConfig from "../types/intelligenceConfig.js";
import type * as types_intelligenceJob from "../types/intelligenceJob.js";
import type * as types_message from "../types/message.js";
import type * as types_note from "../types/note.js";
import type * as types_project from "../types/project.js";
import type * as types_prompt from "../types/prompt.js";
import type * as types_rateLimit from "../types/rateLimit.js";
import type * as types_referral from "../types/referral.js";
import type * as types_shard from "../types/shard.js";
import type * as types_sharedContent from "../types/sharedContent.js";
import type * as types_sharedNote from "../types/sharedNote.js";
import type * as types_stardust from "../types/stardust.js";
import type * as types_subscriptionPlan from "../types/subscriptionPlan.js";
import type * as types_toolCall from "../types/toolCall.js";
import type * as types_translation from "../types/translation.js";
import type * as types_usageEvent from "../types/usageEvent.js";
import type * as types_user from "../types/user.js";
import type * as types_userActivityCounter from "../types/userActivityCounter.js";
import type * as types_userPreference from "../types/userPreference.js";
import type * as types_webhookEvent from "../types/webhookEvent.js";
import type * as types_widgets from "../types/widgets.js";
import type * as usageEvents from "../usageEvents.js";
import type * as userActions from "../userActions.js";
import type * as userMutations from "../userMutations.js";
import type * as userQueries from "../userQueries.js";
import type * as vectorSearch from "../vectorSearch.js";
import type * as vectorSearchMutations from "../vectorSearchMutations.js";
import type * as webhookEvents from "../webhookEvents.js";
import type * as widgetContentMutations from "../widgetContentMutations.js";
import type * as widgetsMutations from "../widgetsMutations.js";
import type * as widgetsQueries from "../widgetsQueries.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  a2aMutations: typeof a2aMutations;
  a2aQueries: typeof a2aQueries;
  agnoRunEvents: typeof agnoRunEvents;
  ambientInsights: typeof ambientInsights;
  apiKeys: typeof apiKeys;
  apiKeysMutations: typeof apiKeysMutations;
  apiKeysQueries: typeof apiKeysQueries;
  artifactMutations: typeof artifactMutations;
  artifactQueries: typeof artifactQueries;
  artifactVersionQueries: typeof artifactVersionQueries;
  assignmentFingerprintMutations: typeof assignmentFingerprintMutations;
  assignmentFingerprintQueries: typeof assignmentFingerprintQueries;
  auth: typeof auth;
  backgroundJobs: typeof backgroundJobs;
  briefingRoomHelpers: typeof briefingRoomHelpers;
  briefingRoomInternal: typeof briefingRoomInternal;
  briefingRoomMutations: typeof briefingRoomMutations;
  briefingRoomQueries: typeof briefingRoomQueries;
  chatModelSelectionBandit: typeof chatModelSelectionBandit;
  chatMutations: typeof chatMutations;
  chatQueries: typeof chatQueries;
  chatgptImport: typeof chatgptImport;
  claudeImport: typeof claudeImport;
  cognitiveMutations: typeof cognitiveMutations;
  cognitiveQueries: typeof cognitiveQueries;
  contentAccessHelpers: typeof contentAccessHelpers;
  contentSharingMutations: typeof contentSharingMutations;
  contentSharingQueries: typeof contentSharingQueries;
  contextEnrichmentBandit: typeof contextEnrichmentBandit;
  contextUsageMutations: typeof contextUsageMutations;
  contextUsageQueries: typeof contextUsageQueries;
  convergenceBestConfigMutations: typeof convergenceBestConfigMutations;
  convergenceBestConfigQueries: typeof convergenceBestConfigQueries;
  convergenceCurrentConfigMutations: typeof convergenceCurrentConfigMutations;
  convergenceCurrentConfigQueries: typeof convergenceCurrentConfigQueries;
  convergenceOptimizationRuns: typeof convergenceOptimizationRuns;
  convergencePresetMutations: typeof convergencePresetMutations;
  convergencePresetQueries: typeof convergencePresetQueries;
  convergenceStorageMutations: typeof convergenceStorageMutations;
  convergenceStorageQueries: typeof convergenceStorageQueries;
  conversationSummariesMutations: typeof conversationSummariesMutations;
  conversationSummariesQueries: typeof conversationSummariesQueries;
  crons: typeof crons;
  crystalCache: typeof crystalCache;
  crystalContextOptimized: typeof crystalContextOptimized;
  crystalMutations: typeof crystalMutations;
  crystalQueries: typeof crystalQueries;
  feedback: typeof feedback;
  folderMutations: typeof folderMutations;
  folderQueries: typeof folderQueries;
  formationMutations: typeof formationMutations;
  formationQueries: typeof formationQueries;
  friendshipMutations: typeof friendshipMutations;
  friendshipQueries: typeof friendshipQueries;
  http: typeof http;
  intelligenceActions: typeof intelligenceActions;
  intelligenceBandit: typeof intelligenceBandit;
  intelligenceConfig: typeof intelligenceConfig;
  intelligenceMutations: typeof intelligenceMutations;
  intelligenceQueries: typeof intelligenceQueries;
  internal: typeof internal_;
  "lib/hash": typeof lib_hash;
  messagesMutations: typeof messagesMutations;
  messagesQueries: typeof messagesQueries;
  "migrations/fixFreeTierSubscriptions": typeof migrations_fixFreeTierSubscriptions;
  "migrations/migrateConversationMessages": typeof migrations_migrateConversationMessages;
  "migrations/migrateFingerprintsToAssignments": typeof migrations_migrateFingerprintsToAssignments;
  "migrations/migrateReservedShards": typeof migrations_migrateReservedShards;
  "migrations/migrateToConvexWidgetIds": typeof migrations_migrateToConvexWidgetIds;
  "migrations/migrateWidgetsToIndividualDocs": typeof migrations_migrateWidgetsToIndividualDocs;
  "migrations/runMigration": typeof migrations_runMigration;
  migrations: typeof migrations;
  noteMutations: typeof noteMutations;
  noteQueries: typeof noteQueries;
  noteSharing: typeof noteSharing;
  notes: typeof notes;
  operationalTransform: typeof operationalTransform;
  paginatedQueries: typeof paginatedQueries;
  platformRouter: typeof platformRouter;
  presence: typeof presence;
  priceConfig: typeof priceConfig;
  projectContentQueries: typeof projectContentQueries;
  projectPresence: typeof projectPresence;
  projectWidgetsMutations: typeof projectWidgetsMutations;
  projectWidgetsQueries: typeof projectWidgetsQueries;
  projectsMutations: typeof projectsMutations;
  projectsQueries: typeof projectsQueries;
  promptsMutations: typeof promptsMutations;
  promptsQueries: typeof promptsQueries;
  rateLimiting: typeof rateLimiting;
  referrals: typeof referrals;
  setAdminRole: typeof setAdminRole;
  shardLifecycleMutations: typeof shardLifecycleMutations;
  shardLifecycleQueries: typeof shardLifecycleQueries;
  shardMutations: typeof shardMutations;
  shardQueries: typeof shardQueries;
  shardStatusManager: typeof shardStatusManager;
  stardustMutations: typeof stardustMutations;
  stardustQueries: typeof stardustQueries;
  subscriptionActions: typeof subscriptionActions;
  subscriptionPlansMutations: typeof subscriptionPlansMutations;
  subscriptionPlansQueries: typeof subscriptionPlansQueries;
  subscriptionQueries: typeof subscriptionQueries;
  testHelpers: typeof testHelpers;
  toolCallMutations: typeof toolCallMutations;
  translationMutations: typeof translationMutations;
  translationQueries: typeof translationQueries;
  "types/a2aNote": typeof types_a2aNote;
  "types/agnoRunEvent": typeof types_agnoRunEvent;
  "types/ambientInsight": typeof types_ambientInsight;
  "types/apiKey": typeof types_apiKey;
  "types/artifact": typeof types_artifact;
  "types/artifactVersion": typeof types_artifactVersion;
  "types/assignmentFingerprint": typeof types_assignmentFingerprint;
  "types/backgroundJob": typeof types_backgroundJob;
  "types/backgroundJobs": typeof types_backgroundJobs;
  "types/briefingCluster": typeof types_briefingCluster;
  "types/briefingEvent": typeof types_briefingEvent;
  "types/briefingPreferences": typeof types_briefingPreferences;
  "types/chatModelSelectionArm": typeof types_chatModelSelectionArm;
  "types/chatModelSelectionDecision": typeof types_chatModelSelectionDecision;
  "types/cognitiveField": typeof types_cognitiveField;
  "types/contentEmbedding": typeof types_contentEmbedding;
  "types/contextEnrichmentArm": typeof types_contextEnrichmentArm;
  "types/contextEnrichmentDecision": typeof types_contextEnrichmentDecision;
  "types/contextUsage": typeof types_contextUsage;
  "types/convergenceBestConfig": typeof types_convergenceBestConfig;
  "types/convergenceCurrentConfig": typeof types_convergenceCurrentConfig;
  "types/convergencePresetConfig": typeof types_convergencePresetConfig;
  "types/convergenceStorage": typeof types_convergenceStorage;
  "types/conversation": typeof types_conversation;
  "types/conversationSummary": typeof types_conversationSummary;
  "types/crystal": typeof types_crystal;
  "types/crystalCache": typeof types_crystalCache;
  "types/crystalFormationRun": typeof types_crystalFormationRun;
  "types/crystalIntelligence": typeof types_crystalIntelligence;
  "types/dataImport": typeof types_dataImport;
  "types/embeddingQueue": typeof types_embeddingQueue;
  "types/embeddingSync": typeof types_embeddingSync;
  "types/embeddingUpdate": typeof types_embeddingUpdate;
  "types/embeddings": typeof types_embeddings;
  "types/feedback": typeof types_feedback;
  "types/folder": typeof types_folder;
  "types/friendship": typeof types_friendship;
  "types/index": typeof types_index;
  "types/intelligenceBandit": typeof types_intelligenceBandit;
  "types/intelligenceBanditArm": typeof types_intelligenceBanditArm;
  "types/intelligenceBanditDecision": typeof types_intelligenceBanditDecision;
  "types/intelligenceConfig": typeof types_intelligenceConfig;
  "types/intelligenceJob": typeof types_intelligenceJob;
  "types/message": typeof types_message;
  "types/note": typeof types_note;
  "types/project": typeof types_project;
  "types/prompt": typeof types_prompt;
  "types/rateLimit": typeof types_rateLimit;
  "types/referral": typeof types_referral;
  "types/shard": typeof types_shard;
  "types/sharedContent": typeof types_sharedContent;
  "types/sharedNote": typeof types_sharedNote;
  "types/stardust": typeof types_stardust;
  "types/subscriptionPlan": typeof types_subscriptionPlan;
  "types/toolCall": typeof types_toolCall;
  "types/translation": typeof types_translation;
  "types/usageEvent": typeof types_usageEvent;
  "types/user": typeof types_user;
  "types/userActivityCounter": typeof types_userActivityCounter;
  "types/userPreference": typeof types_userPreference;
  "types/webhookEvent": typeof types_webhookEvent;
  "types/widgets": typeof types_widgets;
  usageEvents: typeof usageEvents;
  userActions: typeof userActions;
  userMutations: typeof userMutations;
  userQueries: typeof userQueries;
  vectorSearch: typeof vectorSearch;
  vectorSearchMutations: typeof vectorSearchMutations;
  webhookEvents: typeof webhookEvents;
  widgetContentMutations: typeof widgetContentMutations;
  widgetsMutations: typeof widgetsMutations;
  widgetsQueries: typeof widgetsQueries;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
