import { useRouter } from 'next/navigation';
import { useContentContextActions } from '@/store/content-context-store';

/**
 * Custom hook for handling action step discussions in Content Hub
 * Provides functionality to navigate to chat with proper context for content hub action steps
 */
export const useContentHubActionStepDiscussion = () => {
  const router = useRouter();
  const { setAIInsightsContext } = useContentContextActions();

  /**
   * Navigate to chat with the content hub action step as context
   * @param actionStep The action step text to discuss
   * @param insightTitle The title of the insight that contains this action step
   * @param platform The platform the insight is related to (youtube, instagram, gmail)
   * @param additionalContext Optional additional context about the insight
   * @param contentType The type of content (hook, format, cta)
   */
  const discussActionStep = (
    actionStep: string, 
    insightTitle: string,
    platform: 'youtube' | 'instagram' | 'gmail',
    contentType: 'hook' | 'format' | 'cta',
    additionalContext?: string
  ) => {
    console.log('🔍 [CONTENT HUB ACTION STEP] Function called with:', { actionStep, insightTitle, platform, contentType, additionalContext });
    
    // Create a rich context object with detailed information
    const context = {
      platform: 'ai-insights' as const, // Use ai-insights platform for compatibility
      contentId: `content-hub-action-step-${Date.now()}`,
      title: `${platform.charAt(0).toUpperCase() + platform.slice(1)} ${contentType.charAt(0).toUpperCase() + contentType.slice(1)}`,
      content: `## ${platform.charAt(0).toUpperCase() + platform.slice(1)} ${contentType.charAt(0).toUpperCase() + contentType.slice(1)}

${actionStep}

**Platform:** ${platform.charAt(0).toUpperCase() + platform.slice(1)}
**Content Type:** ${contentType.charAt(0).toUpperCase() + contentType.slice(1)}
**Source:** Content Hub Insights

${additionalContext ? `\n**Additional Context:**\n${additionalContext}` : ''}`,
      insight: actionStep, // Also set as insight for backwards compatibility
      source: 'Content Hub Insights',
      originalPlatform: platform, // Add originalPlatform for proper display
      timestamp: Date.now(),
      type: 'content-hub-action-step',
      contentType: contentType,
      additionalContext: additionalContext || ''
    };
    
    console.log('🔍 [CONTENT HUB ACTION STEP] Setting AI insights context:', context);
    setAIInsightsContext(context);
    
    // Small delay to ensure context is set before navigation
    setTimeout(() => {
      console.log('🔍 [CONTENT HUB ACTION STEP] Navigating to chat');
      router.push('/dashboard/chat');
    }, 100);
  };

  /**
   * Navigate to chat with the full content hub insight as context
   * @param content The full content to discuss
   * @param title The title of the insight
   */
  const discussFullInsight = (content: string, title: string) => {
    const context = {
      platform: 'ai-insights' as const, // Use ai-insights platform for compatibility
      contentId: `content-hub-insight-${Date.now()}`,
      title: title,
      content: `## ${title}

${content}

**Source:** Content Hub Insights
**Type:** Cross-Platform Remix Opportunity

This insight was generated by analyzing your content across multiple platforms to identify strategic opportunities for content remixing and cross-platform growth.`,
      insight: content, // Also set as insight for backwards compatibility
      source: 'Content Hub Insights',
      timestamp: Date.now(),
      type: 'content-hub-insight'
    };
    
    console.log('🔍 [CONTENT HUB] Setting AI insights context:', context);
    setAIInsightsContext(context);
    
    // Small delay to ensure context is set before navigation
    setTimeout(() => {
      console.log('🔍 [CONTENT HUB] Navigating to chat');
      router.push('/dashboard/chat');
    }, 100);
  };

  return { discussActionStep, discussFullInsight };
}; 