import React from "react";

const formStyles: { [key: string]: React.CSSProperties } = {
  container: {
    padding: '16px',
    maxWidth: '460px',
    margin: '0 auto',
    maxHeight: '80vh',
    overflowY: 'auto',
    position: 'relative',
  },
  title: {
    fontSize: '1.25rem',
    fontWeight: 600,
    marginBottom: '16px',
    color: '#1f2937',
  },
  formGroup: {
    marginBottom: '16px',
  },
  label: {
    display: 'block',
    marginBottom: '6px',
    fontWeight: 500,
    color: '#374151',
    fontSize: '0.9rem',
  },
  input: {
    width: '100%',
    padding: '8px 12px',
    borderRadius: '6px',
    border: '1px solid #d1d5db',
    fontSize: '0.9rem',
    color: '#374151',
  },
  textarea: {
    width: '100%',
    padding: '8px 12px',
    borderRadius: '6px',
    border: '1px solid #d1d5db',
    minHeight: '80px',
    resize: 'vertical',
    fontSize: '0.9rem',
    fontFamily: 'inherit',
  },
  buttonRow: {
    display: 'flex',
    justifyContent: 'space-between',
    marginTop: '20px',
    gap: '8px',
  },
  button: {
    padding: '8px 16px',
    borderRadius: '6px',
    border: 'none',
    fontSize: '0.9rem',
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  buttonPrimary: {
    backgroundColor: '#7c3aed',
    color: 'white',
  },
  buttonDisabled: {
    backgroundColor: '#e5e7eb',
    color: '#9ca3af',
    cursor: 'not-allowed',
  },
  buttonCancel: {
    backgroundColor: 'transparent',
    color: '#4b5563',
    border: '1px solid #d1d5db',
  },
  hint: {
    color: '#6b7280',
    fontSize: '0.8rem',
    marginTop: '4px',
  },
  platformCard: {
    padding: '10px',
    borderRadius: '6px',
    border: '1px solid #e5e7eb',
    cursor: 'pointer',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '6px',
  },
  platformCardSelected: {
    // Use borderWidth and borderStyle from parent, only change color
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#7c3aed',
    backgroundColor: '#f5f3ff',
  },
  platformIcon: {
    width: '24px',
    height: '24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '6px',
    color: 'white',
    fontSize: '14px',
  },
  platformText: {
    flexGrow: 1,
  },
  platformTitle: {
    fontWeight: 600,
    marginBottom: '2px',
    fontSize: '0.9rem',
  },
  platformDesc: {
    fontSize: '0.8rem',
    color: '#6b7280',
  },
  contentTypeGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '8px',
    marginTop: '8px',
  },
  contentTypeCard: {
    padding: '8px',
    borderRadius: '6px',
    border: '1px solid #e5e7eb',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  contentTypeCardSelected: {
    borderColor: '#7c3aed',
    backgroundColor: '#f5f3ff',
  },
  contentTypeName: {
    fontWeight: 600,
    marginBottom: '2px',
    fontSize: '0.85rem',
  },
  contentTypeDesc: {
    fontSize: '0.75rem',
    color: '#6b7280',
  },
  suggestionsSection: {
    marginTop: '12px',
    padding: '10px',
    backgroundColor: '#f9fafb',
    borderRadius: '6px',
    border: '1px solid #e5e7eb',
  },
  suggestionsTitle: {
    fontWeight: 600,
    marginBottom: '8px',
    fontSize: '0.85rem',
    color: '#4b5563',
  },
  suggestionsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    maxHeight: '150px',
    overflowY: 'auto',
  },
  suggestionItem: {
    padding: '6px 10px',
    backgroundColor: 'white',
    borderRadius: '4px',
    fontSize: '0.8rem',
    cursor: 'pointer',
    border: '1px solid #e5e7eb',
  },
  errorMessage: {
    color: '#ef4444',
    marginBottom: '16px',
    padding: '8px',
    backgroundColor: '#fee2e2',
    borderRadius: '4px',
    fontSize: '0.85rem',
  },
  loadingSpinner: {
    display: 'inline-block',
    width: '32px',
    height: '32px',
    border: '3px solid rgba(124, 58, 237, 0.2)',
    borderTopColor: '#7c3aed',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  }
};

export { formStyles };