/**
 * Widget Panel Component
 * 
 * Displays project widget families in a scrollable panel.
 * Uses direct Convex query following convex-frontend-data-display.md pattern.
 * 
 * CRITICAL: Uses api.widgetsQueries.getProjectWidgets (correct query)
 * PATTERN: Copied from ArtifactPanel.tsx structure
 */

'use client'

import React, { useState } from 'react'
import { useQuery, useMutation } from 'convex/react'
import { useRouter } from 'next/navigation'
import { api } from '../../../../../convex/_generated/api'
import { Id } from '../../../../../convex/_generated/dataModel'
import { Card } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { ExternalLink, BarChart3, Info, Plus, Play } from 'lucide-react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import remarkBreaks from 'remark-breaks'
// import { WidgetScheduleControls } from '@/app/dashboard/living-projects/[projectId]/components/widgets/WidgetScheduleControls'
import { useAdminAuth } from '@/app/lib/admin-auth'
import { formatTimeAgo } from '@/lib/widget-utils'
import { StatusBadge } from '@/components/ui/status-badge'
import { runWidget } from '@/lib/services/widgetService'
import type { InsightEntry } from '../../../../../convex/types/assignmentFingerprint'

interface WidgetPanelProps {
  projectId?: string
  conversationId?: string
  userId: string
  className?: string
}

/**
 * Widget Panel - Clean separation from LabCompositions
 * 
 * Queries widgets table and renders with progressive disclosure.
 * Handles loading, empty, and error states.
 * 
 * CRITICAL: Every widget is tied to one conversation and one project.
 * If projectId is not provided, gets it from conversation.
 * userId is always required for security.
 */
export const WidgetPanel: React.FC<WidgetPanelProps> = ({ 
  projectId, 
  conversationId,
  userId,
  className = '' 
}) => {
  const router = useRouter()
  const { isAdmin } = useAdminAuth()
  
  // Get conversation to extract projectId if not provided
  const conversation = useQuery(
    api.chatQueries.getConversation,
    (!projectId && conversationId) ? {
      userId,
      conversationId: conversationId as Id<"conversations">
    } : "skip"
  )
  
  // Determine the actual projectId to use (from prop or conversation)
  const effectiveProjectId = projectId || (conversation?.projectId as string | undefined)
  
  // Query widgets from widgets table
  // CRITICAL: userId is always required for security
  // CRITICAL: Query in component (NOT in store) - follows convex-frontend-data-display.md
  // CRITICAL: Skip query if projectId is not available yet
  
    // Direct Convex query for widgets (families)
  const widgets = useQuery(
    api.widgetsQueries.getProjectWidgets,
    effectiveProjectId ? {
      projectId: effectiveProjectId as any,
      userId
    } : "skip"
  )
  
  // Query assignment fingerprint for the project
  const fingerprint = useQuery(
    api.assignmentFingerprintQueries.getByProject,
    effectiveProjectId ? {
      projectId: effectiveProjectId as any,
      userId
    } : "skip"
  )
  
  // Query cognitive field for the project
  const cognitiveField = useQuery(
    api.cognitiveQueries.queryCognitiveField,
    effectiveProjectId ? {
      userId,
      useIndex: "by_project",
      indexFields: { projectId: effectiveProjectId },
      limit: 1,
      orderBy: "desc"
    } : "skip"
  )
  
  // Navigation state for showing one widget at a time
  const [currentIndex, setCurrentIndex] = useState(0)
  
  // Current widget being displayed
  const currentWidget = widgets?.[currentIndex]
  
  // Query widget execution prompts (generated by widget_prompt_generator.py)
  const widgetPrompts = useQuery(
    api.promptsQueries.queryPromptsByScope,
    currentWidget?._id ? {
      scope: "widget",
      scopeId: currentWidget._id,
      limit: 20
    } : "skip"
  )
  
  // Collapsible state for progressive disclosure
  const [agentTeamOpen, setAgentTeamOpen] = useState(false)
  const [collaborationOpen, setCollaborationOpen] = useState(false)
  const [fingerprintOpen, setFingerprintOpen] = useState(false)
  const [cognitiveFieldOpen, setCognitiveFieldOpen] = useState(false)
  const [promptsOpen, setPromptsOpen] = useState(false)
  
  // Insight form state
  const [showAddInsightForm, setShowAddInsightForm] = useState(false)
  const [newInsight, setNewInsight] = useState<{ insight: string; category: string; confidence: number }>({
    insight: '',
    category: 'goals',
    confidence: 0.8
  })
  
  // Rerun button state
  const [isRerunning, setIsRerunning] = useState(false)
  const [rerunError, setRerunError] = useState<string | null>(null)
  
  // Mutation for adding insights
  const addInsight = useMutation(api.assignmentFingerprintMutations.mutateAssignmentFingerprint)
  
  // Handle widget rerun
  const handleRerun = async () => {
    if (!currentWidget?._id || !effectiveProjectId || isRerunning) return
    
    setIsRerunning(true)
    setRerunError(null)
    
    try {
      await runWidget({
        widgetId: String(currentWidget._id),
        projectId: effectiveProjectId
      })
      // Success - widget will update via Convex reactivity
      console.log('[WidgetPanel] Widget rerun successful')
    } catch (error: any) {
      console.error('[WidgetPanel] Widget rerun failed:', error)
      
      // Handle 429 rate limit/cooldown errors with user-friendly message
      // Backend returns detail in errorData.detail, which widgetService includes in error.message
      if (error.message?.includes('429') || error.message?.includes('Rate limit') || error.message?.includes('cooldown') || error.message?.includes('Cooldown')) {
        // Error.message already contains the detail from backend (e.g., "Rate limit exceeded. Retry after 300 seconds.")
        setRerunError(error.message || 'Rate limit exceeded. Please wait before rerunning.')
      } else {
        setRerunError(error.message || 'Failed to rerun widget. Please try again.')
      }
    } finally {
      setIsRerunning(false)
    }
  }

  // Loading state - waiting for conversation or widgets
  const isLoadingConversation = !projectId && conversationId && conversation === undefined
  const isLoadingWidgets = effectiveProjectId && widgets === undefined

  if (isLoadingConversation || isLoadingWidgets) {
    return (
      <div className={`h-full flex items-center justify-center p-6 ${className}`}>
        <div className="text-center text-muted-foreground">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto mb-4"></div>
          <p className="text-sm">Loading widgets...</p>
        </div>
      </div>
    )
  }

  // Empty state - no widgets yet
  if (!widgets || widgets.length === 0) {
    return (
      <div className={`h-full flex items-center justify-center p-6 ${className}`}>
        <div className="text-center text-muted-foreground">
          <p className="text-lg">No widgets yet</p>
          <p className="text-sm mt-2">Widgets will appear here as you work with your project</p>
          {effectiveProjectId && (
            <p className="text-xs mt-4 opacity-60">
              Project ID: {effectiveProjectId}
            </p>
          )}
        </div>
      </div>
    )
  }
  
  const hasNext = currentIndex < widgets.length - 1
  const hasPrev = currentIndex > 0
  
  // Navigation handlers
  const goNext = () => {
    if (hasNext) {
      setCurrentIndex(currentIndex + 1)
      // Reset collapsible state when navigating
      setAgentTeamOpen(false)
      setCollaborationOpen(false)
    }
  }
  
  const goPrev = () => {
    if (hasPrev) {
      setCurrentIndex(currentIndex - 1)
      // Reset collapsible state when navigating
      setAgentTeamOpen(false)
      setCollaborationOpen(false)
    }
  }
  

  // Display widgets with progressive disclosure
  return (
    <TooltipProvider>
      <div className={`h-full overflow-y-auto p-4 bg-background ${className}`}>
        <div className="space-y-4">
          {/* Header - Always visible */}
          <Card className="bg-card/50 backdrop-blur-sm border border-border/40">
            <div className="p-6">
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-3">
                  <BarChart3 className="w-6 h-6 text-primary" />
                  <h2 className="text-2xl font-bold text-foreground">
                    {currentWidget.familyIdentity?.familyName || currentWidget.title}
                  </h2>
                </div>
                <div className="flex items-center gap-2">
                  <StatusBadge 
                    status={currentWidget.lastRunStatus === 'running' ? 'active' 
                          : currentWidget.lastRunStatus === 'completed' ? 'completed'
                          : currentWidget.lastRunStatus === 'error' ? 'error'
                          : 'idle'} 
                    size="sm"
                  />
                  {effectiveProjectId && currentWidget._id && (
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={handleRerun}
                      disabled={isRerunning || currentWidget.lastRunStatus === 'running'}
                      className="min-h-[44px] min-w-[44px]"
                    >
                      {isRerunning ? (
                        <>
                          <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-primary mr-2"></div>
                          Running...
                        </>
                      ) : (
                        <>
                          <Play className="w-4 h-4 mr-2" />
                          Rerun
                        </>
                      )}
                    </Button>
                  )}
                </div>
              </div>
              
              {rerunError && (
                <div className="mb-4 p-3 bg-destructive/10 border border-destructive/20 rounded-lg">
                  <p className="text-sm text-destructive">{rerunError}</p>
                </div>
              )}
              
              <p className="text-muted-foreground text-lg mb-4">
                {currentWidget.familyIdentity?.mission || currentWidget.description || 'Helps you manage your project'}
              </p>
              
              {/* Widget Schedule Controls */}
              {/* {effectiveProjectId && currentWidget._id && (
                <div className="mb-4">
                  <WidgetScheduleControls
                    widgetId={String(currentWidget._id)}
                    projectId={effectiveProjectId}
                    isScheduled={currentWidget.scheduleEnabled || false}
                    nextScheduledRun={currentWidget.nextScheduledRun || null}
                    frequency={currentWidget.scheduleFrequency || 'daily'}
                    suggestedFrequency={currentWidget.executionProfile?.frequencySuggestion || null}
                    isAdmin={isAdmin}
                    onScheduleChange={() => {
                      // Trigger a refetch of widget data if needed
                      // The component will update via Convex reactivity
                    }}
                  />
                </div>
              )} */}
            </div>
          </Card>
          
          {/* Agent Team - Collapsible */}
          {currentWidget.agentRoster && currentWidget.agentRoster.length > 0 && (
            <Collapsible open={agentTeamOpen} onOpenChange={setAgentTeamOpen}>
              <CollapsibleTrigger asChild>
                <Button variant="ghost" className="w-full justify-start">
                  {agentTeamOpen ? "Hide Agent Team" : `Show Agent Team (${currentWidget.agentRoster.length})`}
                </Button>
              </CollapsibleTrigger>
              <CollapsibleContent>
                <Card className="bg-card/50 backdrop-blur-sm border border-border/40 mt-2">
                  <div className="p-6">
                    <h3 className="text-lg font-semibold text-foreground mb-4">
                      Agent Team
                      {' '}
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <Info className="w-4 h-4 text-blue-500 inline cursor-help" />
                        </TooltipTrigger>
                        <TooltipContent>
                          <p>A helper is like a team member that handles one specific task.</p>
                          <p>They work together to get things done.</p>
                        </TooltipContent>
                      </Tooltip>
                    </h3>
                    
                    <div className="space-y-3">
                      {currentWidget.agentRoster.map((agent: any, idx: number) => (
                        <div key={idx} className="bg-purple-500/10 border-l-4 border-purple-500 p-4 rounded">
                          <p className="font-semibold text-foreground">
                            {idx + 1}. {agent.roleName}
                          </p>
                          <p className="text-sm text-muted-foreground mt-1">
                            → {agent.responsibilities?.[0] || agent.personality}
                          </p>
                          <p className="text-xs text-muted-foreground mt-2">
                            {agent.spawnCondition === 'Always active' 
                              ? 'Always working' 
                              : `Starts ${agent.spawnCondition?.toLowerCase() || 'when needed'}`}
                          </p>
                        </div>
                      ))}
                    </div>
                  </div>
                </Card>
              </CollapsibleContent>
            </Collapsible>
          )}
          
          {/* Collaboration Style - Collapsible */}
          {currentWidget.familyIdentity?.collaborationStyle && (
            <Collapsible open={collaborationOpen} onOpenChange={setCollaborationOpen}>
              <CollapsibleTrigger asChild>
                <Button variant="ghost" className="w-full justify-start">
                  {collaborationOpen ? "Hide details" : "How They Work Together"}
                </Button>
              </CollapsibleTrigger>
              <CollapsibleContent>
                <Card className="bg-card/50 backdrop-blur-sm border border-border/40 mt-2">
                  <div className="p-6">
                    <h3 className="text-lg font-semibold text-foreground mb-4">
                      How They Work Together
                    </h3>
                    
                    <div className="bg-muted/20 border border-border/30 rounded-lg p-4 mb-4">
                      <p className="text-sm font-medium text-foreground mb-2">Collaboration Style:</p>
                      <p className="text-sm text-foreground whitespace-pre-wrap">
                        {currentWidget.familyIdentity.collaborationStyle}
                      </p>
                    </div>
                    
                    {currentWidget.familyIdentity.qualityStandard && (
                      <div className="bg-muted/20 border border-border/30 rounded-lg p-4">
                        <p className="text-sm font-medium text-foreground mb-2">Quality Standard:</p>
                        <p className="text-sm text-foreground whitespace-pre-wrap">
                          {currentWidget.familyIdentity.qualityStandard}
                        </p>
                      </div>
                    )}
                  </div>
                </Card>
              </CollapsibleContent>
            </Collapsible>
          )}
          
          {/* Assignment Fingerprint - Collapsible */}
          {fingerprint && (
            <Collapsible open={fingerprintOpen} onOpenChange={setFingerprintOpen}>
              <CollapsibleTrigger asChild>
                <Button variant="ghost" className="w-full justify-start">
                  {fingerprintOpen ? "Hide fingerprint" : `Assignment Fingerprint ${fingerprint._id ? `(${fingerprint._id.slice(0, 8)}...)` : ''}`}
                </Button>
              </CollapsibleTrigger>
              <CollapsibleContent>
                <Card className="bg-card/50 backdrop-blur-sm border border-border/40 mt-2">
                  <div className="p-6">
                    <div className="flex items-center justify-between mb-4">
                      <h3 className="text-lg font-semibold text-foreground">
                        Assignment Fingerprint
                      </h3>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => setShowAddInsightForm(!showAddInsightForm)}
                      >
                        <Plus className="w-4 h-4 mr-2" />
                        Add Insight
                      </Button>
                    </div>
                    
                    {/* Add Insight Form */}
                    {showAddInsightForm && (
                      <div className="bg-muted/20 border border-border/30 rounded-lg p-4 mb-4">
                        <h4 className="text-sm font-medium text-foreground mb-3">Add New Insight</h4>
                        <div className="space-y-3">
                          <div>
                            <label className="text-xs text-muted-foreground mb-1 block">Category</label>
                            <Select
                              value={newInsight.category}
                              onValueChange={(value) => setNewInsight({ ...newInsight, category: value })}
                            >
                              <SelectTrigger>
                                <SelectValue />
                              </SelectTrigger>
                              <SelectContent>
                                <SelectItem value="goals">Goals</SelectItem>
                                <SelectItem value="constraints">Constraints</SelectItem>
                                <SelectItem value="timeline">Timeline</SelectItem>
                                <SelectItem value="people">People</SelectItem>
                                <SelectItem value="requirements">Requirements</SelectItem>
                                <SelectItem value="context">Context</SelectItem>
                                <SelectItem value="artifacts_needed">Artifacts Needed</SelectItem>
                                <SelectItem value="help_wanted">Help Wanted</SelectItem>
                                <SelectItem value="working_style">Working Style</SelectItem>
                              </SelectContent>
                            </Select>
                          </div>
                          <div>
                            <label className="text-xs text-muted-foreground mb-1 block">Insight</label>
                            <Textarea
                              value={newInsight.insight}
                              onChange={(e) => setNewInsight({ ...newInsight, insight: e.target.value })}
                              placeholder="Enter your insight..."
                              rows={3}
                            />
                          </div>
                          <div className="flex gap-2">
                            <Button
                              size="sm"
                              onClick={async () => {
                                if (!newInsight.insight.trim() || !effectiveProjectId) return
                                
                                const insightEntry: InsightEntry = {
                                  id: crypto.randomUUID(),
                                  insight: newInsight.insight.trim(),
                                  timestamp: Date.now(),
                                  conversationId: conversationId || '',
                                  messageCount: 0,
                                  confidence: newInsight.confidence,
                                  category: newInsight.category,
                                }
                                
                                try {
                                  await addInsight({
                                    operation: 'addUserInsight',
                                    projectId: effectiveProjectId as Id<'projects'>,
                                    userId,
                                    userInsight: insightEntry,
                                  })
                                  
                                  // Reset form
                                  setNewInsight({ insight: '', category: 'goals', confidence: 0.8 })
                                  setShowAddInsightForm(false)
                                } catch (error) {
                                  console.error('Failed to add insight:', error)
                                }
                              }}
                              disabled={!newInsight.insight.trim()}
                            >
                              Save
                            </Button>
                            <Button
                              size="sm"
                              variant="ghost"
                              onClick={() => {
                                setShowAddInsightForm(false)
                                setNewInsight({ insight: '', category: 'goals', confidence: 0.8 })
                              }}
                            >
                              Cancel
                            </Button>
                          </div>
                        </div>
                      </div>
                    )}
                    
                    {/* Group insights by category */}
                    {(() => {
                      const insights = fingerprint.insights || []
                      const groupedInsights: Record<string, InsightEntry[]> = {}
                      
                      insights.forEach((insight: InsightEntry) => {
                        const category = insight.category || 'other'
                        if (!groupedInsights[category]) {
                          groupedInsights[category] = []
                        }
                        groupedInsights[category].push(insight)
                      })
                      
                      // Sort insights within each category by timestamp (newest first)
                      Object.keys(groupedInsights).forEach(category => {
                        groupedInsights[category].sort((a, b) => b.timestamp - a.timestamp)
                      })
                      
                      const categoryLabels: Record<string, string> = {
                        goals: 'Goals',
                        constraints: 'Constraints',
                        timeline: 'Timeline',
                        people: 'People',
                        requirements: 'Requirements',
                        context: 'Context',
                        artifacts_needed: 'Artifacts Needed',
                        help_wanted: 'Help Wanted',
                        working_style: 'Working Style',
                      }
                      
                      return (
                        <div className="space-y-4">
                          {Object.keys(groupedInsights).length === 0 ? (
                            <div className="bg-muted/20 border border-border/30 rounded-lg p-4 text-center">
                              <p className="text-sm text-muted-foreground">No insights yet. Add one above!</p>
                            </div>
                          ) : (
                            Object.keys(groupedInsights).map((category) => (
                              <div key={category} className="bg-muted/20 border border-border/30 rounded-lg p-4">
                                <h4 className="text-sm font-medium text-foreground mb-3">
                                  {categoryLabels[category] || category}
                                  <Badge variant="outline" className="ml-2 text-xs">
                                    {groupedInsights[category].length}
                                  </Badge>
                                </h4>
                                <div className="space-y-2">
                                  {groupedInsights[category].map((insight: InsightEntry) => (
                                    <div
                                      key={insight.id}
                                      className="bg-background/50 rounded p-3 border border-border/20"
                                    >
                                      <div className="prose prose-sm max-w-none break-words text-sm text-foreground mb-2">
                                        <ReactMarkdown remarkPlugins={[remarkGfm, remarkBreaks]}>
                                          {insight.insight}
                                        </ReactMarkdown>
                                      </div>
                                      <div className="flex items-center gap-3 text-xs text-muted-foreground">
                                        <span>
                                          {new Date(insight.timestamp).toLocaleDateString()} {new Date(insight.timestamp).toLocaleTimeString()}
                                        </span>
                                        {insight.confidence !== undefined && (
                                          <Badge variant="outline" className="text-xs">
                                            {(insight.confidence * 100).toFixed(0)}% confidence
                                          </Badge>
                                        )}
                                        {insight.conversationId && (
                                          <span className="text-xs opacity-60">
                                            Conversation: {insight.conversationId.slice(0, 8)}...
                                          </span>
                                        )}
                                      </div>
                                    </div>
                                  ))}
                                </div>
                              </div>
                            ))
                          )}
                          
                          {/* Summary Stats */}
                          {fingerprint.totalInsights !== undefined && (
                            <div className="bg-muted/20 border border-border/30 rounded-lg p-4">
                              <p className="text-sm font-medium text-foreground mb-2">Summary</p>
                              <p className="text-sm text-foreground">
                                {fingerprint.totalInsights} total insights across {Object.keys(groupedInsights).length} categories
                              </p>
                              {fingerprint.currentGoals && fingerprint.currentGoals.length > 0 && (
                                <p className="text-xs text-muted-foreground mt-2">
                                  Current Goals: {fingerprint.currentGoals.length}
                                </p>
                              )}
                              {fingerprint.currentConstraints && fingerprint.currentConstraints.length > 0 && (
                                <p className="text-xs text-muted-foreground">
                                  Current Constraints: {fingerprint.currentConstraints.length}
                                </p>
                              )}
                            </div>
                          )}
                        </div>
                      )
                    })()}
                  </div>
                </Card>
              </CollapsibleContent>
            </Collapsible>
          )}
          
          {/* Widget Execution Prompts - Collapsible */}
          {widgetPrompts && Array.isArray(widgetPrompts) && widgetPrompts.length > 0 && (
            <Collapsible open={promptsOpen} onOpenChange={setPromptsOpen}>
              <CollapsibleTrigger asChild>
                <Button variant="ghost" className="w-full justify-start">
                  {promptsOpen ? "Hide prompts" : `Execution Prompts (${widgetPrompts.length})`}
                </Button>
              </CollapsibleTrigger>
              <CollapsibleContent>
                <Card className="bg-card/50 backdrop-blur-sm border border-border/40 mt-2">
                  <div className="p-6">
                    <h3 className="text-lg font-semibold text-foreground mb-4">
                      Execution Prompts
                      {' '}
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <Info className="w-4 h-4 text-blue-500 inline cursor-help" />
                        </TooltipTrigger>
                        <TooltipContent>
                          <p>Custom prompts generated for this widget's agents.</p>
                          <p>These prompts are used when the widget runs operations.</p>
                        </TooltipContent>
                      </Tooltip>
                    </h3>
                    
                    <div className="space-y-4">
                      {widgetPrompts.map((prompt: any, idx: number) => {
                        // Extract operation from tags (e.g., "information_check", "planning")
                        const operationTag = prompt.tags?.find((tag: string) => 
                          ['information_check', 'planning', 'generation', 'validation'].includes(tag)
                        ) || prompt.tags?.[0] || 'unknown';
                        
                        return (
                          <div key={prompt._id || idx} className="bg-blue-500/10 border-l-4 border-blue-500 p-4 rounded">
                            <div className="flex items-start justify-between mb-2">
                              <div className="flex-1">
                                <div className="flex items-center gap-2 mb-1">
                                  <Badge variant="outline" className="text-xs">
                                    {operationTag}
                                  </Badge>
                                  {prompt.effectiveness !== undefined && (
                                    <Badge 
                                      variant="outline" 
                                      className={`text-xs ${
                                        prompt.effectiveness >= 0.8 
                                          ? 'bg-green-500/20 text-green-600 dark:text-green-400'
                                          : prompt.effectiveness >= 0.5
                                          ? 'bg-yellow-500/20 text-yellow-600 dark:text-yellow-400'
                                          : 'bg-muted/20'
                                      }`}
                                    >
                                      {(prompt.effectiveness * 100).toFixed(0)}% effective
                                    </Badge>
                                  )}
                                  {prompt.usageCount !== undefined && prompt.usageCount > 0 && (
                                    <Badge variant="outline" className="text-xs">
                                      Used {prompt.usageCount}x
                                    </Badge>
                                  )}
                                </div>
                                {prompt.description && (
                                  <p className="text-xs text-muted-foreground mb-2">
                                    {prompt.description}
                                  </p>
                                )}
                              </div>
                            </div>
                            
                            <div className="bg-background/50 rounded p-3 mt-2">
                              <p className="text-xs text-foreground whitespace-pre-wrap font-mono">
                                {prompt.content}
                              </p>
                            </div>
                            
                            {prompt.version && (
                              <p className="text-xs text-muted-foreground mt-2">
                                Version {prompt.version}
                              </p>
                            )}
                          </div>
                        );
                      })}
                    </div>
                  </div>
                </Card>
              </CollapsibleContent>
            </Collapsible>
          )}
          
          {/* Cognitive Field - Collapsible */}
          {cognitiveField && Array.isArray(cognitiveField) && cognitiveField.length > 0 && (() => {
            const field = cognitiveField[0];
            const transparency = field.transparencyLayer;
            const semantic = field.semanticMetadata;
            const crossDomain = field.crossDomainLayer;
            const coreField = field.coreField;
            
            
            return (
              <Collapsible open={cognitiveFieldOpen} onOpenChange={setCognitiveFieldOpen}>
              <CollapsibleTrigger asChild>
                <Button variant="ghost" className="w-full justify-start">
                  {cognitiveFieldOpen ? "Hide cognitive field" : `Cognitive Field ${field?.fieldId ? `(${field.fieldId.slice(0, 8)}...)` : ''}`}
                </Button>
              </CollapsibleTrigger>
                <CollapsibleContent>
                  <Card className="bg-card/50 backdrop-blur-sm border border-border/40 mt-2">
                    <div className="p-6 space-y-4">
                      {/* Header with Status */}
                      <div className="flex items-center justify-between mb-4">
                        <h3 className="text-lg font-semibold text-foreground">
                          Cognitive Field
                        </h3>
                        {field.status && (
                          <StatusBadge 
                            status={field.status === 'active' ? 'active' 
                                  : field.status === 'archived' ? 'idle' 
                                  : 'completed'} 
                            size="sm" 
                          />
                        )}
                      </div>
                      
                      {/* Human-Readable Summary (Transparency Layer) */}
                      {transparency?.interpretiveSummary && (
                        <div className="bg-blue-500/10 border-l-4 border-blue-500 rounded-lg p-4">
                          <p className="text-sm font-medium text-foreground mb-2">Understanding</p>
                          <p className="text-sm text-foreground whitespace-pre-wrap">
                            {transparency.interpretiveSummary}
                          </p>
                        </div>
                      )}
                      
                      {/* Human Label */}
                      {transparency?.humanLabel && (
                        <div className="bg-muted/20 border border-border/30 rounded-lg p-4">
                          <p className="text-sm font-medium text-foreground mb-1">Label:</p>
                          <p className="text-sm text-foreground">{transparency.humanLabel}</p>
                        </div>
                      )}
                      
                      {/* Key Metrics Grid */}
                      <div className="grid grid-cols-2 gap-3">
                        {field.usageCount !== undefined && (
                          <div className="bg-muted/20 border border-border/30 rounded-lg p-3">
                            <p className="text-xs text-muted-foreground mb-1">Usage Count</p>
                            <p className="text-lg font-semibold text-foreground">{field.usageCount}</p>
                          </div>
                        )}
                        {field.lastUsed && (
                          <div className="bg-muted/20 border border-border/30 rounded-lg p-3">
                            <p className="text-xs text-muted-foreground mb-1">Last Used</p>
                            <p className="text-sm font-semibold text-foreground">{formatTimeAgo(field.lastUsed)} ago</p>
                          </div>
                        )}
                        {transparency?.stabilityScore !== undefined && (
                          <div className="bg-muted/20 border border-border/30 rounded-lg p-3">
                            <p className="text-xs text-muted-foreground mb-1">Stability</p>
                            <p className="text-lg font-semibold text-foreground">
                              {(transparency.stabilityScore * 100).toFixed(0)}%
                            </p>
                          </div>
                        )}
                        {field.createdAt && (
                          <div className="bg-muted/20 border border-border/30 rounded-lg p-3">
                            <p className="text-xs text-muted-foreground mb-1">Created</p>
                            <p className="text-sm font-semibold text-foreground">{formatTimeAgo(field.createdAt)} ago</p>
                          </div>
                        )}
                      </div>
                      
                      {/* Abstract Dimensions (Semantic Layer) */}
                      {semantic?.abstractDimensions && semantic.abstractDimensions.length > 0 && (
                        <div className="bg-muted/20 border border-border/30 rounded-lg p-4">
                          <p className="text-sm font-medium text-foreground mb-3">Abstract Dimensions</p>
                          <div className="space-y-2">
                            {semantic.abstractDimensions.map((dim: any, idx: number) => (
                              <div key={idx} className="flex items-center justify-between">
                                <span className="text-sm text-foreground">{dim.dimensionName || `Dimension ${idx + 1}`}</span>
                                <div className="flex items-center gap-2">
                                  <div className="w-24 h-2 bg-muted rounded-full overflow-hidden">
                                    <div 
                                      className="h-full bg-primary rounded-full transition-all"
                                      style={{ width: `${Math.min(100, Math.max(0, (dim.value || 0) * 100))}%` }}
                                    />
                                  </div>
                                  <span className="text-xs text-muted-foreground w-12 text-right">
                                    {(dim.value || 0).toFixed(2)}
                                  </span>
                                </div>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}
                      
                      {/* Meta Inference Summary */}
                      {semantic?.metaInferenceSummary && (
                        <div className="bg-purple-500/10 border-l-4 border-purple-500 rounded-lg p-4">
                          <p className="text-sm font-medium text-foreground mb-2">Meta Inference</p>
                          <p className="text-sm text-foreground whitespace-pre-wrap">
                            {semantic.metaInferenceSummary}
                          </p>
                        </div>
                      )}
                      
                      {/* Cross-Domain Patterns */}
                      {crossDomain?.crossDomainPatterns && crossDomain.crossDomainPatterns.length > 0 && (
                        <div className="bg-muted/20 border border-border/30 rounded-lg p-4">
                          <p className="text-sm font-medium text-foreground mb-3">Cross-Domain Patterns</p>
                          <div className="space-y-3">
                            {crossDomain.crossDomainPatterns.map((pattern: any, idx: number) => (
                              <div key={idx} className="bg-background/50 rounded p-3">
                                <p className="text-sm font-semibold text-foreground mb-1">
                                  {pattern.name || `Pattern ${idx + 1}`}
                                </p>
                                {pattern.description && (
                                  <p className="text-xs text-muted-foreground mb-2">{pattern.description}</p>
                                )}
                                {pattern.domains && pattern.domains.length > 0 && (
                                  <div className="flex flex-wrap gap-1 mt-2">
                                    {pattern.domains.map((domain: string, dIdx: number) => (
                                      <Badge key={dIdx} variant="outline" className="text-xs">
                                        {domain}
                                      </Badge>
                                    ))}
                                  </div>
                                )}
                                {pattern.noveltyScore !== undefined && (
                                  <p className="text-xs text-muted-foreground mt-2">
                                    Novelty: {(pattern.noveltyScore * 100).toFixed(0)}%
                                  </p>
                                )}
                              </div>
                            ))}
                          </div>
                        </div>
                      )}
                      
                      {/* Emergent Themes */}
                      {crossDomain?.emergentThemes && crossDomain.emergentThemes.length > 0 && (
                        <div className="bg-muted/20 border border-border/30 rounded-lg p-4">
                          <p className="text-sm font-medium text-foreground mb-3">Emergent Themes</p>
                          <div className="flex flex-wrap gap-2">
                            {crossDomain.emergentThemes.map((theme: string, idx: number) => (
                              <Badge key={idx} className="bg-yellow-500/20 text-yellow-700 dark:text-yellow-400 border-0">
                                {theme}
                              </Badge>
                            ))}
                          </div>
                        </div>
                      )}
                      
                      {/* Temporal Drift */}
                      {crossDomain?.temporalDrift && (
                        <div className="bg-orange-500/10 border-l-4 border-orange-500 rounded-lg p-4">
                          <p className="text-sm font-medium text-foreground mb-2">Temporal Drift</p>
                          {crossDomain.temporalDrift.direction && (
                            <p className="text-sm text-foreground mb-2">
                              <span className="font-semibold">Direction:</span> {crossDomain.temporalDrift.direction}
                            </p>
                          )}
                          {crossDomain.temporalDrift.description && (
                            <p className="text-sm text-foreground mb-2 whitespace-pre-wrap">
                              {crossDomain.temporalDrift.description}
                            </p>
                          )}
                          {crossDomain.temporalDrift.keyChanges && crossDomain.temporalDrift.keyChanges.length > 0 && (
                            <div className="mt-2">
                              <p className="text-xs font-medium text-foreground mb-1">Key Changes:</p>
                              <ul className="list-disc list-inside space-y-1">
                                {crossDomain.temporalDrift.keyChanges.map((change: string, idx: number) => (
                                  <li key={idx} className="text-xs text-foreground">{change}</li>
                                ))}
                              </ul>
                            </div>
                          )}
                        </div>
                      )}
                      
                      {/* Source Tracking */}
                      {((field.sourceShardIds && field.sourceShardIds.length > 0) || 
                       (field.sourceStardustIds && field.sourceStardustIds.length > 0)) && (
                        <div className="bg-muted/20 border border-border/30 rounded-lg p-4">
                          <p className="text-sm font-medium text-foreground mb-2">Sources</p>
                          {field.sourceShardIds && field.sourceShardIds.length > 0 && (
                            <div className="mb-2">
                              <p className="text-xs text-muted-foreground mb-1">Shards ({field.sourceShardIds.length}):</p>
                              <div className="flex flex-wrap gap-1">
                                {field.sourceShardIds.slice(0, 3).map((id: string, idx: number) => (
                                  <Badge key={idx} variant="outline" className="text-xs font-mono">
                                    {id.slice(0, 8)}...
                                  </Badge>
                                ))}
                                {field.sourceShardIds.length > 3 && (
                                  <Badge variant="outline" className="text-xs">
                                    +{field.sourceShardIds.length - 3} more
                                  </Badge>
                                )}
                              </div>
                            </div>
                          )}
                          {field.sourceStardustIds && field.sourceStardustIds.length > 0 && (
                            <div>
                              <p className="text-xs text-muted-foreground mb-1">Stardust ({field.sourceStardustIds.length}):</p>
                              <div className="flex flex-wrap gap-1">
                                {field.sourceStardustIds.slice(0, 3).map((id: string, idx: number) => (
                                  <Badge key={idx} variant="outline" className="text-xs font-mono">
                                    {id.slice(0, 8)}...
                                  </Badge>
                                ))}
                                {field.sourceStardustIds.length > 3 && (
                                  <Badge variant="outline" className="text-xs">
                                    +{field.sourceStardustIds.length - 3} more
                                  </Badge>
                                )}
                              </div>
                            </div>
                          )}
                        </div>
                      )}
                      
                      {/* Field ID (Technical) */}
                      <div className="bg-muted/20 border border-border/30 rounded-lg p-3">
                        <p className="text-xs text-muted-foreground mb-1">Field ID:</p>
                        <p className="text-xs text-foreground font-mono break-all">
                          {field.fieldId || 'N/A'}
                        </p>
                      </div>
                      
                      {/* Core Field Stats (if available) */}
                      {coreField && (
                        <div className="bg-muted/20 border border-border/30 rounded-lg p-4">
                          <p className="text-sm font-medium text-foreground mb-2">Core Field Stats</p>
                          <div className="grid grid-cols-2 gap-2 text-xs">
                            {coreField.fieldNodes && (
                              <div>
                                <span className="text-muted-foreground">Nodes: </span>
                                <span className="text-foreground font-semibold">{coreField.fieldNodes.length}</span>
                              </div>
                            )}
                            {coreField.crosslinks && (
                              <div>
                                <span className="text-muted-foreground">Crosslinks: </span>
                                <span className="text-foreground font-semibold">{coreField.crosslinks.length}</span>
                              </div>
                            )}
                            {coreField.lastProcessed && (
                              <div className="col-span-2">
                                <span className="text-muted-foreground">Last Processed: </span>
                                <span className="text-foreground">{formatTimeAgo(coreField.lastProcessed)} ago</span>
                              </div>
                            )}
                          </div>
                        </div>
                      )}
                    </div>
                  </Card>
                </CollapsibleContent>
              </Collapsible>
            );
          })()}
          
          {/* Navigation Controls */}
          <div className="flex items-center justify-between pt-4 border-t border-border/20">
            <Button
              variant="ghost"
              onClick={goPrev}
              disabled={!hasPrev}
              className="text-muted-foreground hover:text-foreground disabled:opacity-30"
            >
              ← Previous
            </Button>
            
            <span className="text-sm text-muted-foreground">
              {currentIndex + 1} of {widgets.length}
            </span>
            
            <Button
              variant="ghost"
              onClick={goNext}
              disabled={!hasNext}
              className="text-muted-foreground hover:text-foreground disabled:opacity-30"
            >
              Next →
            </Button>
          </div>
          
          {/* Open in Assignment View Button */}
          {effectiveProjectId && currentWidget && (
            <div className="pt-4 border-t border-border/20 mt-4">
              <Button
                variant="outline"
                className="w-full"
                onClick={() => {
                  router.push(`/dashboard/living-projects/${effectiveProjectId}/assignment`)
                }}
              >
                <ExternalLink className="w-4 h-4 mr-2" />
                Open in Assignment View
              </Button>
            </div>
          )}
        </div>
      </div>
    </TooltipProvider>
  )
}

