import React, { useMemo } from 'react';
import { useQuery } from 'convex/react';
import { api } from '@/convex/_generated/api';
import { InsightCard } from '@/components/ui/insight-card';
import { CenterContainer, ContentWrapper } from '@/components/ui/layout';
import { Sparkles, MessageSquare } from 'lucide-react';

interface WidgetPromptsProps {
  widgetOutputId: string;
  userId: string;
  onPromptClick?: (promptText: string) => void;
}

// Layout wrapper for consistent styling
const PromptsContainer: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <CenterContainer variant="full">
    <ContentWrapper maxWidth="xl" className="px-6">
      {children}
    </ContentWrapper>
  </CenterContainer>
);

/**
 * WidgetPrompts Component
 * 
 * Displays conversation prompts generated by a widget execution.
 * Fetches widget output by outputId and displays prompts in a clean, actionable format.
 */
export const WidgetPrompts: React.FC<WidgetPromptsProps> = ({ 
  widgetOutputId,
  userId,
  onPromptClick
}) => {
  // Fetch widget output data from Convex
  // When limit: 1, returns a single object (not an array)
  const widgetOutputData = useQuery(
    api.widgetOutputsQueries.getWidgetOutputData,
    widgetOutputId && userId ? { 
      userId,
      filters: { outputId: widgetOutputId },
      limit: 1
    } : 'skip'
  );

  console.log('[WidgetPrompts] Component render:', {
    widgetOutputId,
    userId: userId ? 'present' : 'missing',
    dataStatus: widgetOutputData === undefined ? 'loading' : widgetOutputData ? 'loaded' : 'null'
  });

  // Parse widget output data
  const parsedOutput = useMemo(() => {
    if (!widgetOutputData) return null;
    
    // Handle both single object (limit: 1) and array responses
    const output = Array.isArray(widgetOutputData) 
      ? widgetOutputData[0] 
      : widgetOutputData;
    
    console.log('[WidgetPrompts] Query result:', widgetOutputData);
    console.log('[WidgetPrompts] Parsed output:', output);
    console.log('[WidgetPrompts] Prompts array:', output?.prompts);
    
    return output;
  }, [widgetOutputData]);

  // Transform prompts into sorted array
  const prompts = useMemo(() => {
    if (!parsedOutput?.prompts || !Array.isArray(parsedOutput.prompts)) {
      console.log('[WidgetPrompts] No prompts found or invalid format');
      return [];
    }

    console.log('[WidgetPrompts] Found', parsedOutput.prompts.length, 'prompts');
    
    return parsedOutput.prompts.sort((a, b) => a.priority - b.priority);
  }, [parsedOutput]);

  // Loading state
  if (widgetOutputData === undefined) {
    return (
      <PromptsContainer>
        <div className="space-y-4">
          {[1, 2, 3].map((i) => (
            <div key={i} className="h-48 bg-muted/30 rounded-lg animate-pulse" />
          ))}
        </div>
      </PromptsContainer>
    );
  }

  // No prompts found
  if (prompts.length === 0) {
    return (
      <PromptsContainer>
        <div className="text-center py-12 space-y-4">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-muted">
            <MessageSquare className="w-8 h-8 text-muted-foreground" />
          </div>
          <div className="space-y-2">
            <h3 className="text-lg font-semibold text-foreground">
              No Conversation Prompts
            </h3>
            <p className="text-sm text-muted-foreground max-w-md mx-auto">
              This widget execution didn't generate any conversation prompts.
            </p>
          </div>
        </div>
      </PromptsContainer>
    );
  }

  return (
    <PromptsContainer>
      <div className="space-y-4 py-4">
        {/* Header */}
        <div className="flex items-center gap-3">
          <div className="inline-flex items-center justify-center w-10 h-10 rounded-full bg-blue-500/10">
            <Sparkles className="w-5 h-5 text-blue-600 dark:text-blue-400" />
          </div>
          <div>
            <h2 className="text-lg sm:text-xl font-light text-foreground">
              Conversation Starters
            </h2>
            <p className="text-xs text-muted-foreground">
              Click any prompt to start exploring
            </p>
          </div>
        </div>

        {/* Prompt Cards - Horizontal grid layout */}
        <div className="grid grid-cols-2 lg:grid-cols-3 gap-4">
          {prompts.map((prompt, index) => (
            <InsightCard
              key={`prompt-${widgetOutputId}-${index}`}
              title={`Prompt ${index + 1}`}
              description={prompt.text}
              icon={<MessageSquare className="w-6 h-6" />}
              onClick={() => onPromptClick?.(prompt.text)}
              variant="compact"
            />
          ))}
        </div>
      </div>
    </PromptsContainer>
  );
};

