/**
 * A2A (Agent-to-Agent) Service
 * 
 * Fetches inter-agent communication messages for displaying widget activity.
 * Follows Pattern 1 (Full-Stack API Call) from patterns.md:
 * - Uses fetchWithApiKey for auth (no userId in params)
 * - Calls Next.js API route (/api/a2a/latest) which proxies to backend
 * - Backend extracts userId from Authorization header
 * 
 * WHY: A2A messages are stored in Convex but fetched via HTTP endpoint
 * because they're generated by backend agents and need real-time activity
 * visibility in the progressive disclosure UI.
 * 
 * @see patterns.md Pattern 1: The Full-Stack API Call
 */
import { fetchWithApiKey } from '@/app/lib/api-helpers'

export const a2aService = {
  /**
   * Get latest A2A messages for a project
   * 
   * @param projectId - Project ID to fetch messages for
   * @param limit - Maximum number of messages to return (default: 10)
   * @returns Promise resolving to A2A messages response
   * @throws Error if API request fails
   * 
   * WHY HTTP instead of Convex query: A2A messages are generated by backend
   * agents during execution and stored via HTTP endpoint. Frontend needs
   * real-time visibility into agent activity for "What's Happening" section.
   */
  async getLatest(projectId: string, limit = 10) {
    // Pattern 1 compliance: fetchWithApiKey handles auth, no userId param
    const response = await fetchWithApiKey('/api/a2a/latest', {
      method: 'POST',
      body: JSON.stringify({ projectId, limit })
    })
    
    if (!response.ok) {
      throw new Error(`A2A fetch failed with status ${response.status}`)
    }
    
    return response.json()
  }
}

