'use client'

import React from 'react'
import { MessageSquare, Plus, Pause } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { Progress } from '@/components/ui/progress'
import { cn } from '@/lib/utils'

interface AssignmentCardLargeProps {
  assignment: any
  progress: number
  timeLeft: string
  onPause?: () => void
  isPausing?: boolean
  className?: string
}

/**
 * AssignmentCardLarge - Large active assignment card
 * 
 * Matches Figma design exactly:
 * - 742px x 232px
 * - Blue border (2px solid, uses --assignment-primary-blue)
 * - Card background (uses --card CSS variable, adapts to light/dark mode)
 * - Progress bar (404px width, orange)
 * - Action buttons (Discuss In Chat, New Widget, Pause)
 */
export function AssignmentCardLarge({
  assignment,
  progress,
  timeLeft,
  onPause,
  isPausing = false,
  className
}: AssignmentCardLargeProps) {
  const router = useRouter()

  // Get project conversation for "Discuss In Chat"
  const handleDiscussInChat = () => {
    if (assignment.conversationId) {
      router.push(`/dashboard/thinking_lab?conversationId=${assignment.conversationId}`)
    } else if (assignment._id) {
      router.push(`/dashboard/thinking_lab?projectId=${assignment._id}`)
    }
  }

  // Handle new widget
  const handleNewWidget = () => {
    if (assignment._id) {
      router.push(`/dashboard/living-projects/${assignment._id}`)
    }
  }

  // Format relative time
  const relativeTime = (() => {
    if (!assignment.updatedAt && !assignment._creationTime) return '2 hours ago'
    const date = new Date(assignment.updatedAt || assignment._creationTime)
    const now = Date.now()
    const diff = now - date.getTime()
    const hours = Math.floor(diff / (1000 * 60 * 60))
    const days = Math.floor(hours / 24)
    
    if (hours < 1) return 'Just now'
    if (hours < 24) return `${hours} hour${hours !== 1 ? 's' : ''} ago`
    if (days < 7) return `${days} day${days !== 1 ? 's' : ''} ago`
    return date.toLocaleDateString()
  })()

  return (
    <a
      className={cn(
        "bg-[hsl(var(--card))] border-2 border-[hsl(var(--assignment-primary-blue))] border-solid cursor-pointer relative rounded-[8px] shrink-0 w-[742px] h-[232px]",
        "transition-all hover:border-[hsl(var(--assignment-primary-blue))]/80",
        className
      )}
      onClick={() => {
        if (assignment._id) {
          router.push(`/dashboard/living-projects/${assignment._id}/assignment`)
        }
      }}
    >
      {/* Exact from Figma: Frame 185 x="20" y="20" width="702" height="72" */}
      <div className="box-border content-stretch flex flex-col gap-[20px] items-start overflow-clip p-[20px] relative rounded-[inherit] w-full">
        {/* Title and Timestamp - Exact from Figma: Frame 185 x="0" y="0" width="702" height="72" */}
        <div className="content-stretch flex font-['DM_Sans'] font-semibold items-center justify-between leading-[0] relative shrink-0 text-[hsl(var(--assignment-text-regular))] w-full" style={{ fontVariationSettings: "'opsz' 14, 'opsz' 14" }}>
          <div className="flex flex-[1_0_0] flex-col justify-center min-h-px min-w-px relative shrink-0 text-[24px] tracking-[-0.72px]">
            <p className="leading-[36px] whitespace-pre-wrap line-clamp-3">
              {assignment.name || 'this might be autogenerated unless you bothered to name them'}
            </p>
          </div>
          <div className="flex flex-col justify-center relative shrink-0 text-[0px] tracking-[-0.48px] whitespace-nowrap" style={{ fontVariationSettings: "'opsz' 14, 'opsz' 14" }}>
            <p className="font-['DM_Sans'] font-semibold leading-[24px] text-[16px]">
              {relativeTime}
            </p>
          </div>
        </div>

        {/* Progress Bar and Pause - Exact from Figma: Frame 186 x="20" y="112" width="702" height="40" */}
        <div className="content-stretch flex items-center justify-between relative shrink-0 w-full">
          <div className="content-stretch flex gap-[24px] items-center relative shrink-0">
            {/* Progress Bar - Exact from Figma: Frame 188 x="0" y="8" width="507" height="24" */}
            <div className="box-border content-stretch flex gap-[8px] items-start pl-[4px] pr-0 py-0 relative shrink-0 w-[404px]">
              <Progress value={progress} className="h-3 flex-1" />
            </div>
            
            {/* Time Left - Exact from Figma: x="428" y="0" width="79" height="24" */}
            <div className="flex flex-col font-['DM_Sans'] font-semibold justify-center leading-[0] relative shrink-0 text-[0px] text-[hsl(var(--assignment-text-subtle))] tracking-[-0.48px] whitespace-nowrap" style={{ fontVariationSettings: "'opsz' 14, 'opsz' 14" }}>
              <p className="font-['DM_Sans'] font-semibold leading-[24px] text-[16px]">
                {timeLeft}
              </p>
            </div>
          </div>

          {/* Pause Button - Exact from Figma: Frame 189 x="598" y="0" width="104" height="40" */}
          <div className="content-stretch flex gap-[24px] items-center relative shrink-0">
            <button
              onClick={(e) => {
                e.stopPropagation()
                onPause?.()
              }}
              disabled={isPausing}
              className="bg-transparent box-border content-stretch flex gap-[8px] isolate items-center justify-center overflow-clip px-[16px] py-[8px] relative rounded-[12px] shrink-0 text-[hsl(var(--assignment-error))] hover:bg-transparent hover:text-[hsl(var(--assignment-error))]/80 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <Pause className="overflow-clip relative shrink-0 size-[24px] z-[3] text-[hsl(var(--assignment-error))]" />
              <div className="flex flex-col font-['DM_Sans'] font-semibold justify-center leading-[0] relative shrink-0 text-[hsl(var(--assignment-error))] text-[14px] tracking-[-0.14px] whitespace-nowrap z-[2]" style={{ fontVariationSettings: "'opsz' 14, 'opsz' 14" }}>
                <p className="leading-[21px]">Pause</p>
              </div>
            </button>
          </div>
        </div>

        {/* Action Buttons - Exact from Figma: Frame 188 x="20" y="172" width="702" height="40" */}
        <div className="content-stretch flex gap-[20px] items-center relative shrink-0 w-full">
          {/* Discuss In Chat - Exact from Figma: Button x="0" y="0" width="166" height="40" */}
          <button
            onClick={(e) => {
              e.stopPropagation()
              handleDiscussInChat()
            }}
            className="bg-[hsl(var(--assignment-primary-blue))] box-border content-stretch flex gap-[8px] isolate items-center justify-center overflow-clip px-[16px] py-[8px] relative rounded-[12px] shrink-0"
          >
            <MessageSquare className="overflow-clip relative shrink-0 size-[24px] z-[3] text-[hsl(var(--assignment-primary-blue-text))]" />
            <div className="flex flex-col font-['DM_Sans'] font-semibold justify-center leading-[0] relative shrink-0 text-[hsl(var(--assignment-primary-blue-text))] text-[14px] tracking-[-0.14px] whitespace-nowrap z-[2]" style={{ fontVariationSettings: "'opsz' 14, 'opsz' 14" }}>
              <p className="leading-[21px]">Discuss In Chat</p>
            </div>
          </button>

          {/* New Widget - Exact from Figma: Frame 188 x="186" y="0" width="145" height="40" */}
          <div className="content-stretch flex gap-[24px] items-center relative shrink-0">
            <button
              onClick={(e) => {
                e.stopPropagation()
                handleNewWidget()
              }}
              className="bg-[hsl(var(--assignment-accent-orange))] box-border content-stretch flex gap-[8px] isolate items-center justify-center overflow-clip px-[16px] py-[8px] relative rounded-[12px] shrink-0"
            >
              <Plus className="overflow-clip relative shrink-0 size-[24px] z-[3] text-[hsl(var(--assignment-accent-orange-text))]" />
              <div className="flex flex-col font-['DM_Sans'] font-semibold justify-center leading-[0] relative shrink-0 text-[hsl(var(--assignment-accent-orange-text))] text-[14px] tracking-[-0.14px] whitespace-nowrap z-[2]" style={{ fontVariationSettings: "'opsz' 14, 'opsz' 14" }}>
                <p className="leading-[21px]">New Widget</p>
              </div>
            </button>
          </div>
        </div>
      </div>
    </a>
  )
}

